### ISSUE TITLE
I can't resize render sequence window

### ISSUE THREAD

**Issue by SheziTheArtist** [artineering-io/MNPRX#11]
**Describe the bug**
The top white bar window disappears to the top of my screen and I can't bring the window down. I reset the window or resize it so it is stuck on my screen unless I close Maya

**To Reproduce**
1. Go to 'Render Sequence window in Maya with Flair 1.1.2'
2. Click on 'The top bar and hide it or try to resize window'

**Expected behavior**
I should be able to resize window or at least move it without the top bar as a workaround.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [Maya 2024]
 - The contents of Maya's _Output Window_ (you may remove any sensitive information)
: INITIALIZING FLAIR (Build: Aug 16 2024)
-> Creating render override
-> Plugin environment set to: D:/Flair Setup/Flair 1.1.2/maya
-> Shader directory added: D:/Flair Setup/Flair 1.1.2/maya/shaders
Flair Licensing: Loaded license file (C:/Users/she0006/Documents/maya/flair.lic)
V2 fingerprint: v
Flair Licensing: Validation reply: 
{"data":{"id":"","type":"licenses","attributes":{"name":null,"key":"1b1f18f5632b22818be68039517e992c","expiry":null,"status":"ACTIVE","uses":0,"suspended":false,"scheme":null,"encrypted":false,"strict":true,"floating":true,"protected":true,"version":null,"maxMachines":1,"maxProcesses":null,"maxUsers":null,"maxCores":null,"maxUses":null,"requireHeartbeat":false,"requireCheckIn":false,"lastValidated":"2024-10-23T17:42:40.021Z","lastCheckIn":null,"nextCheckIn":null,"lastCheckOut":null,"metadata":{"invoiceId":"","patreonUserId":"","fastSpringSubscriptionId":"9N7-xJ79QuyP2QQHviT8rQ"},"created":"2024-10-22T19:18:23.216Z","updated":"2024-10-23T17:21:00.472Z"},"relationships":{"account":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542"},"data":{"type":"accounts","id":"04a51224-15ee-41f9-bbf6-db3b9448e542"}},"environment":{"links":{"related":null},"data":null},"product":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/product"},"data":{"type":"products","id":"aea87d3d-d3f7-42a6-8acc-224a5c3caf97"}},"policy":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/policy"},"data":{"type":"policies","id":"77e58101-57e4-487d-9e64-adf3bb699a6e"}},"group":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/group"},"data":null},"users":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/users"},"meta":{"count":0}},"machines":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/machines"},"meta":{"cores":0,"count":1}},"tokens":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/tokens"}},"entitlements":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/entitlements"}},"user":{"links":{"related":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9/user"},"data":null}},"links":{"self":"/v1/accounts/04a51224-15ee-41f9-bbf6-db3b9448e542/licenses/6e936047-d29a-4556-9c96-4491597cdad9"}},"meta":{"ts":"2024-10-23T17:42:40.032Z","valid":true,"detail":"is valid","scope":{"fingerprint":"v2-"},"constant":"VALID"}}
Flair Licensing: Product ID: 
Flair Licensing: Validation successful. Product name: INDIE
Running as INDIE
-> Render Override registered
-> Glad loaded - GL_CONTEXT_COMPATIBILITY_PROFILE
-> Commands registered
-> Nodes registered
-> Callbacks added
-> Materials registered
-> Default material behavior registered
-> Shader override registered
FLAIR INITIALIZED
RESETTING STYLIZATION
Running as INDIE

 - Maya's _Script Editor_ output contents (you may remove any sensitive information)
  import flair_runner
flair_runner.open_target_sequence_renderer()
# INITIALIZING FLAIR (Build: Aug 16 2024)
# Loading render override, please be patient
updateRenderOverride;
# -> flairGlobals created
# coop.qt : Flair Renderer was successfully generated
currentTime 0 ;
OutputWindow;

**Additional context**
![Screenshot (296)](https://github.com/user-attachments/assets/545881f6-89bb-4269-b2c9-2f9e7a048d8f)

**Comment by semontesdeoca** [comment]
Hi @SheziTheArtist,

This is indeed an annoying issue with Qt.
I had to make the window not manually resizable so that it dynamically resizes depending on the AOVs and cameras available in the scene.

There are, however, two ways to bring the window back to a "normal" place.

On Windows, you can always use the classic "move with keyboard". This works on ALL windows :)
1. Make sure the window is currently in "focus"
2. Press "ALT"+ "spacebar" to trigger the window menu
3. Click on "Move"
4. Use the arrow keys on your keyboard to move the window around
5. After moving the window once with your keyboard, you can continue by simply moving the mouse around, the window should follow the cursor now.

With Flair, you can also double click on the tool in the shelf to reset it. So, if you double click on the `seq` shelf button, the Flair renderer will revert to its default position.

I hope this helps!
