### ISSUE TITLE
Maya Crashes With Any Activation

### ISSUE THREAD

**Issue by efranklin176** [artineering-io/MNPRX#4]
Hi, 

The free demo automatically crashed Maya, so I purchased the $25 version in an attempt to make it work. Any time I try to activate the key it crashes. I'm using Maya 2020.

**Comment by ennis** [comment]
Hello,
Thank you for your report. In order for us to track down the issue faster, could you also provide, if that's possible: 
- the contents of Maya's Output Window at the time of the crash
- the contents of Maya's Script Editor at the time of the crash

**Comment by semontesdeoca** [comment]
It would also be useful if you could provide us with the following:

 - OS: [e.g. Windows]
 - Version with update [e.g. Maya 2019.3.1]

**Comment by efranklin176** [comment]
Hi again,

I was using a VMWare program to access my school's PCs so it seemed to be
an issue with them. I contacted them, and they sorted it out. Thank you!

**Comment by semontesdeoca** [comment]
That's great to hear, thanks for reaching out and we hope you enjoy using MNPRX!
