### ISSUE TITLE
Clear Items are White

### ISSUE THREAD

**Issue by efranklin176** [artineering-io/MNPRX#5]
Hi! I'm currently trying to render out a transparent PNG using an alpha on the image so that I can render out PNGs on planes. The parts that are supposed to be transparent render out as white, is there any way to have transparent items render out as transparent?

**Comment by semontesdeoca** [comment]
Hi @efranklin176, what do you have your alpha set to in the renderer?
![image](https://user-images.githubusercontent.com/1998692/109166994-963b0600-777d-11eb-942c-72a4a164adbb.png)

**Comment by efranklin176** [comment]
It's set to none but nothing seems to work. this is how the texture is set up, I'm not sure if this is something that may not work. [
<img width="742" alt="Screen Shot 2021-02-25 at 9 32 30 AM" src="https://user-images.githubusercontent.com/44952416/109168040-6de6e380-774c-11eb-8b30-f8d8c75cd128.png">
](url)

**Comment by semontesdeoca** [comment]
Ok, there are two problems here:

1.- You should use MNPRX materials whenever possible. The Arnold material that you are using probably won't render alpha correctly in the viewport.
2.- When rendering, set the alpha to either premult or linear, depending on what you need in the compositing application.

@efranklin176, I think you have an Indie license or? You can also join the discord to chat with us directly. It might be better than on Github.

**Comment by efranklin176** [comment]
joining the discord now!
