### ISSUE TITLE
How to split AOV channels

### ISSUE THREAD

**Issue by cs344820283** [artineering-io/MNPRX#6]
hi, I want to use its aov layering function, how do I achieve it? grateful

**Comment by cs344820283** [comment]
![montionBlur](https://user-images.githubusercontent.com/92389109/136998882-fb0abb44-8500-4cba-b797-5a46f0df0d50.jpg)
What is the realization of this procedural motion blur effect？thanks

**Comment by semontesdeoca** [comment]
Hi @cs344820283,
Thanks for reaching out. There is no way to do this out-of-the-box in MNPRX. 
We can however develop this for you as part of our [RnD Agency services](https://artineering.io/agency/)

**Comment by semontesdeoca** [comment]
Hi @cs344820283,
Flair 1.1 will now have geometric motion blur effects, so stay tuned for its imminent release!
