### ISSUE TITLE
Batch rendering does not function while MNPRX is installed. 

### ISSUE THREAD

**Issue by ThePortmantologist** [artineering-io/MNPRX#7]
**Describe the bug**
If MNPRX is properly installed in Maya, the batch rendering function of other renderers (vray, Arnold, etc.) does not function. 

**To Reproduce**
1. Successfully install MNPRX to Maya. 
2. Switch to other renderer such as Vray or Arnold
3. Set up a render using non-MNPRX shaders and lights.
4. Set file path. 
5. Navigate to the Rendering shelf in Maya. 
6. Render -> Batch render6. 
7. See error. 

**Expected behavior**
Non-MNPRX renderer should successfully render out an image to the specified file path. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Maya 2020/2022

**Comment by semontesdeoca** [comment]
Hi @ThePortmantologist,
Thank you for the report. This issue has been solved as of Flair 1.0.2
