### ISSUE TITLE
[Bug] Attribute error

### ISSUE THREAD

**Issue by usernameU8879** [artineering-io/MNPRX#8]
**Describe the bug**
cannot do anything after installation

**Screenshots**
![image](https://user-images.githubusercontent.com/117036086/198894119-a68574c8-db25-432f-a7ec-19b11e4095d7.png)
Fruit plate example scenes:
![image](https://user-images.githubusercontent.com/117036086/198894219-904e81b5-3404-4c5c-81d8-2af92c93fb1a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Maya 2020
 - The contents of Maya's _Output Window_ (you may remove any sensitive information)
 - Maya's _Script Editor_ output contents (you may remove any sensitive information)

*

**Comment by semontesdeoca** [comment]
Hi @usernameU8879,

this is not a bug but a wrong installation, please follow the instructions here: https://docs.artineering.io/flair/setup/
If you keep encountering this issue, please reach out to us through Discord to help you out.
