### ISSUE TITLE
transparency object sorting

### ISSUE THREAD

**Issue by JoshF-W** [artineering-io/MNPRX#9]
**Describe the bug**
objects with transparency not maintaining correct object order in depth. 
Object jumps in front and behind other object even though it should always be in front.
wondering if it is a scene scale issue.  

**To Reproduce**
1. made a standard warp shader. with transparency set to.300
2. directional light (resolution of 4096 width focus 500) and spot light  shadow maps 
3. Character is large with transparent arms 
4. Scroll down to '....'
5. See error

**Expected behavior**
I expect the objects to maintain order in depth when transparent.
screen left arm should be in front but appears to be behind

**Screenshots**
![image](https://github.com/artineering-io/MNPRX/assets/155590622/3f72a9f0-dc67-4b4e-8c49-37566536c66b)
![image](https://github.com/artineering-io/MNPRX/assets/155590622/e2864180-c985-4a7e-95c5-8f48c9fc361b)

**Desktop (please complete the following information):**
 - windows 11
 - maya 2024.2

 ____________________________________
[output_window.txt](https://github.com/artineering-io/MNPRX/files/13847811/output_window.txt)
[script_editor.txt](https://github.com/artineering-io/MNPRX/files/13847812/script_editor.txt)

**Comment by semontesdeoca** [comment]
Hi @JoshF-W,

Thank you for the report.
Semi-transparency is currently only handled via object sorting as of Flair 1.1.
Therefore, overlapping semi-transparent objects can sometimes be drawn incorrectly on top of each other, depending on the current object's pivot position relative to the camera.

If you just need opaque-transparent, you can use the alpha mask instead, which won't have this issue.
